# Generated by Django 4.1.3 on 2022-11-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comp', models.CharField(max_length=100)),
                ('codigo_emp', models.CharField(max_length=3)),
                ('celular', models.CharField(max_length=15)),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.posicion')),
            ],
        ),
    ]
