# Generated by Django 4.1.3 on 2022-11-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicion',
            old_name='title',
            new_name='titulo',
        ),
    ]
