# Generated by Django 4.1.3 on 2022-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_rename_title_posicion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='act_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
